import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import AddNewWord from "@/component/AddNewWord";
import Navtop from "@/component/Navtop";
import Providers from "@/component/Providers";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <Providers>
          <div className="drawer drawer-end">
            <input id="my-drawer" type="checkbox" className="drawer-toggle" />
            <div className="drawer-content">
              {/* Page content here */}
              <Navtop />
              {children}
            </div>
            <div className="drawer-side">
              <label
                htmlFor="my-drawer"
                aria-label="close sidebar"
                className="drawer-overlay"
              ></label>
              <div className="menu p-4 w-80 min-h-full bg-base-200 text-base-content">
                {/* Sidebar content here */}
                <AddNewWord />
              </div>
            </div>
          </div>
        </Providers>
      </body>
    </html>
  );
}
